---
abstract: 'A grep-like program for searching source code'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ack
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.22
  Cwd: 3.00
  File::Basename: 1.00015
  File::Glob: 1.00015
  File::Next: 1.10
  File::Spec: 3.00
  File::Temp: 0.19
  Getopt::Long: 2.36
  Pod::Usage: 1.26
  Term::ANSIColor: 3.01
  Test::Harness: 2.50
  Test::More: 0.98
  Text::ParseWords: 3.1
resources:
  bugtracker: http://github.com/petdance/ack2
  homepage: http://betterthangrep.com/
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/petdance/ack2.git
  x_MailingList: http://groups.google.com/group/ack-users
version: 2.00b03
