--- #YAML:1.0
name:                ack
version:             1.76
abstract:            A grep-like program specifically for large source trees
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Basename:                0
    File::Next:                    0.4
    Getopt::Long:                  0
    Term::ANSIColor:               0
    Test::Harness:                 2.5
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Lester <andy@petdance.com>
resources:
    homepage: http://petdance.com/ack/
    bugtracker: http://code.google.com/p/ack/issues/list
    license: http://dev.perl.org/licenses/
    Repository: http://code.google.com/p/ack/source
    MailingList: http://groups.google.com/group/ack-users
