--- #YAML:1.0
name:                ack
version:             1.77_03
abstract:            A grep-like program specifically for large source trees
license:             ~
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    File::Next:                    0.4
    Getopt::Long:                  0
    Term::ANSIColor:               0
    Test::Harness:                 2.5
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
