---
abstract: 'A grep-like program for searching source code'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ack
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 0
  File::Next: 1.1
  Getopt::Long: 2.36
  Pod::Usage: 0
  Term::ANSIColor: 0
  Test::Harness: 2.5
  Test::More: 0.96
resources:
  bugtracker: http://github.com/petdance/ack2
  homepage: http://betterthangrep.com/
  license: http://www.opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/petdance/ack2.git
  x_MailingList: http://groups.google.com/group/ack-users
version: 2.00a01
