--- #YAML:1.0
name:                ack
version:             1.62
abstract:            A grep-like program specifically for large source trees
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Basename:                0
    File::Next:                    0.4
    Getopt::Long:                  0
    Term::ANSIColor:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Lester <andy@petdance.com>
