--- #YAML:1.0
name:                ack
version:             1.56
abstract:            A grep-like program specifically for large source trees
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Andy Lester <andy@petdance.com>
distribution_type:   module
requires:     
    File::Basename:                0
    File::Next:                    0.38
    Getopt::Long:                  0
    Term::ANSIColor:               0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
